Traceback (most recent call last):
  File "main.py", line 12, in <module>
    chdir(dirname(__file__))
FileNotFoundError: [Errno 2] No such file or directory: ''
